repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # https://github.com/samuelcolvin/pydantic/blob/master/Makefile
#  TODO change to local make
#  - repo: local
#    hooks:
#      - id: lint api files
#        name: lint api files
#        entry: cd api && make
#        types: [python]
#        language: system
#      - id: export-api-requirements
#        name: Export api requirements.txt
#        language: system
#        entry: cd api && make export-dependencies
#        files: ^(pyproject.toml|poetry.lock)$
#      - id: lint parser files
#        name: lint parser files
#        entry: cd parser && make
#        types: [ python ]
#        language: system
#      - id: export-parser-requirements
#        name: Export parser requirements.txt
#        language: system
#        entry: cd parser && make export-dependencies
#        files: ^(pyproject.toml|poetry.lock)$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

default_language_version:
  python: python3.10
default_stages: [commit, push]