apiVersion: 1

datasources:
  - name: postgres
    type: postgres
    url: database:5432
    user: example
    database: database
    isDefault: true
    jsonData:
      postgresVersion: 1000
      sslmode: 'disable'
      tlsAuth: false
      tlsAuthWithCACert: false

    secureJsonData:
      password: "example"
      basicAuthPassword: "example"

    version: 1
    editable: true
