"""empty message

Revision ID: 909be6493aeb
Revises: 81d4e0456e95
Create Date: 2022-11-23 22:16:22.051625

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "909be6493aeb"
down_revision = "81d4e0456e95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aggregate_table_model_result",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("quater", sa.Integer(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=True),
        sa.Column("source_site", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("neutral", sa.Integer(), nullable=True),
        sa.Column("positive", sa.Integer(), nullable=True),
        sa.Column("negative", sa.Integer(), nullable=True),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aggregate_table_model_result_quater"), "aggregate_table_model_result", ["quater"], unique=False
    )
    op.create_index(
        op.f("ix_aggregate_table_model_result_year"), "aggregate_table_model_result", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aggregate_table_model_result_year"), table_name="aggregate_table_model_result")
    op.drop_index(op.f("ix_aggregate_table_model_result_quater"), table_name="aggregate_table_model_result")
    op.drop_table("aggregate_table_model_result")
    # ### end Alembic commands ###
