"""empty message

Revision ID: 3a79a22b07ba
Revises: 61e997004b48
Create Date: 2022-11-09 23:43:09.809702

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a79a22b07ba"
down_revision = "61e997004b48"
branch_labels = None
depends_on = None

bank_type = sa.table(
    "bank_type",
    sa.Column("id", sa.Integer()),
    sa.Column("name", sa.String()),
)

bank = sa.table(
    "bank",
    sa.Column("id", sa.Integer()),
    sa.Column("bank_type_id", sa.Integer()),
    sa.Column("bank_name", sa.String()),
    sa.Column("description", sa.String()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(sa.insert(bank_type).values(name="bank"))  # type: ignore
    op.create_index(op.f("ix_bank_type_id"), "bank_type", ["id"], unique=False)
    op.create_index(op.f("ix_bank_type_name"), "bank_type", ["name"], unique=False)
    op.add_column("bank", sa.Column("bank_type_id", sa.Integer(), nullable=True))
    op.execute(sa.update(bank).values(bank_type_id=1))
    op.create_index(op.f("ix_bank_bank_type_id"), "bank", ["bank_type_id"], unique=False)
    op.create_foreign_key(None, "bank", "bank_type", ["bank_type_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bank_bank_type_id_fkey", "bank", type_="foreignkey")
    op.drop_index(op.f("ix_bank_bank_type_id"), table_name="bank")
    op.drop_column("bank", "bank_type_id")
    op.drop_index(op.f("ix_bank_type_name"), table_name="bank_type")
    op.drop_index(op.f("ix_bank_type_id"), table_name="bank_type")
    op.drop_table("bank_type")
    # ### end Alembic commands ###
