"""add_is_processed

Revision ID: e3b13b49a5ac
Revises: f5727821a974
Create Date: 2022-10-25 22:07:51.877432

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3b13b49a5ac"
down_revision = "f5727821a974"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("text_result", sa.Column("is_processed", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_text_sentence_text_id"), "text_sentence", ["text_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_text_sentence_text_id"), table_name="text_sentence")
    op.drop_column("text_result", "is_processed")
    # ### end Alembic commands ###
