"""empty message

Revision ID: 56a380c80e86
Revises: faaa2b068990
Create Date: 2023-02-01 14:38:45.599779

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "56a380c80e86"
down_revision = "faaa2b068990"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_reviews_count",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("quarter", sa.Integer(), nullable=True),
        sa.Column("source_site", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("count_reviews", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_text_reviews_count_date"), "text_reviews_count", ["date"], unique=False)
    op.create_index(op.f("ix_text_reviews_count_quarter"), "text_reviews_count", ["quarter"], unique=False)
    op.create_index(op.f("ix_text_reviews_count_source_site"), "text_reviews_count", ["source_site"], unique=False)
    op.create_index(op.f("ix_text_reviews_count_source_type"), "text_reviews_count", ["source_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_text_reviews_count_source_type"), table_name="text_reviews_count")
    op.drop_index(op.f("ix_text_reviews_count_source_site"), table_name="text_reviews_count")
    op.drop_index(op.f("ix_text_reviews_count_quarter"), table_name="text_reviews_count")
    op.drop_index(op.f("ix_text_reviews_count_date"), table_name="text_reviews_count")
    op.drop_table("text_reviews_count")
    # ### end Alembic commands ###
