"""empty message

Revision ID: fdf4c2482f38
Revises: cab5f2d71e76
Create Date: 2023-03-04 19:02:49.608479

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fdf4c2482f38"
down_revision = "cab5f2d71e76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("aggregate_table_model_result", "year", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("aggregate_table_model_result", "quater", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("aggregate_table_model_result", "model_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("aggregate_table_model_result", "source_site", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("aggregate_table_model_result", "source_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("aggregate_table_model_result", "bank_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("aggregate_table_model_result", "bank_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("aggregate_table_model_result", "positive", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("aggregate_table_model_result", "negative", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("aggregate_table_model_result", "total", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "aggregate_table_model_result", "index_base", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "aggregate_table_model_result", "index_mean", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "aggregate_table_model_result", "index_std", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column(
        "aggregate_table_model_result", "index_safe", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
    )
    op.alter_column("bank", "licence", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("bank", "bank_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("bank_type", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("model", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("model", "model_type_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("model_type", "model_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("source", "site", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("source", "source_type_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_source_id"), "source", ["id"], unique=True)
    op.alter_column("source_type", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_source_type_id"), "source_type", ["id"], unique=True)
    op.alter_column("text", "link", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("text", "source_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text", "date", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("text", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("text", "bank_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_result", "text_sentence_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_result", "model_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_result", "is_processed", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("text_reviews_count", "date", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("text_reviews_count", "quarter", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_reviews_count", "source_site", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("text_reviews_count", "source_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("text_reviews_count", "count_reviews", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_sentence", "text_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("text_sentence", "sentence", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("text_sentence", "sentence_num", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(op.f("ix_text_sentence_id"), "text_sentence", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_text_sentence_id"), table_name="text_sentence")
    op.alter_column("text_sentence", "sentence_num", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text_sentence", "sentence", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("text_sentence", "text_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text_reviews_count", "count_reviews", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text_reviews_count", "source_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("text_reviews_count", "source_site", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("text_reviews_count", "quarter", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text_reviews_count", "date", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("text_result", "is_processed", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("text_result", "model_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text_result", "text_sentence_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text", "bank_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("text", "date", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("text", "source_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("text", "link", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_source_type_id"), table_name="source_type")
    op.alter_column("source_type", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_source_id"), table_name="source")
    op.alter_column("source", "source_type_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("source", "site", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("model_type", "model_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("model", "model_type_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("model", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("bank_type", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("bank", "bank_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("bank", "licence", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "aggregate_table_model_result", "index_safe", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "aggregate_table_model_result", "index_std", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "aggregate_table_model_result", "index_mean", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column(
        "aggregate_table_model_result", "index_base", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    op.alter_column("aggregate_table_model_result", "total", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("aggregate_table_model_result", "negative", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("aggregate_table_model_result", "positive", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("aggregate_table_model_result", "bank_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("aggregate_table_model_result", "bank_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("aggregate_table_model_result", "source_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("aggregate_table_model_result", "source_site", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("aggregate_table_model_result", "model_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("aggregate_table_model_result", "quater", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("aggregate_table_model_result", "year", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
