"""empty message

Revision ID: 3a9a41953764
Revises: 909be6493aeb
Create Date: 2023-01-12 18:30:53.616076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a9a41953764"
down_revision = "909be6493aeb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("aggregate_table_model_result", sa.Column("bank_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("aggregate_table_model_result", "bank_id")
    # ### end Alembic commands ###
