FROM python:3.10

WORKDIR "/app"
ENV PYTHONPATH /app/
COPY requirements/requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app
CMD ["python", "/app/app/view_main.py"]
