services:
  database:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  tests:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: "postgresql+psycopg2://example:example@database/test"
